//
// Created by Ivan Bogatyrev on 12/6/2020.
//

#define MATRIX_MEMORY_ALLOCATION_ERROR 1
#define MATRIX_DATA_INPUT_ERROR 2

#define MATRIX_OUT_OF_RANGE 3
#define MATRIX_RANGE_SUSPECT 31

#define MATRIX_ENLARGEMENT_ERROR 4
#define WRONG_DATA 5
#define MATRIX_MULTIPLICATION_ERROR 6